CC=clang
CXX=gcc
CFLAGS=-I. -I../src/include -shared -Wl,-install_name,
LIBNDPI=ndpi_wrap.c ndpi_util.c ../src/lib/libndpi.a
LDFLAGS=$(LIBNDPI) -lpcap -lpthread 
OBJS=ndpiReader.so
PIC = -fPIC
PREFIX?=/usr/local

all: ndpiReader.so

ndpiReader.so:
	$(CXX) $(CFLAGS)$(OBJS) -o $(OBJS) $(PIC) $(LDFLAGS)
